<?php

namespace Plugin\ProductProfile\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductProfileRepository extends EntityRepository
{
}
